# 1. Import Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import string
import csv
from wordcloud import WordCloud

## 2. Import Preprocessed data

### 2.1 Positive

In [3]:
with open("../bow-data/positive.csv", newline="") as f:
    reader = csv.DictReader(f)
    data = list(reader)

positive_df = pd.DataFrame(data)

# convert dates to datetime
positive_df['at'] = pd.to_datetime(positive_df['at'])

positive_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,fde4f8c6-06c5-4d58-b5d8-2f12540509b6,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,steam app great way interact friends access st...,5,6,3.10.9,2026-03-11 00:07:34,,,3.10.9
1,8448fd1d-9f20-4762-9711-dd77a0d750d2,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,like interface lot think easy use main reason ...,5,223,3.10.5,2025-08-16 16:09:10,,,3.10.5
2,61cf9985-2aba-407a-95da-c046e37ad094,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,steam best refund game buy like constant disco...,5,0,3.10.7,2026-03-17 23:04:08,,,3.10.7
3,26f389ce-a7fd-4ecd-983c-c873414a13e5,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,steam honestly one greatest apps ever make cou...,5,33,3.10.7,2026-02-25 00:37:11,,,3.10.7
4,f43d8462-bf9c-4594-88de-3bc03905da19,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,tf2 tf2 tf2 tf2 get wrong absolutely terrible ...,5,2,3.10.9,2026-03-13 09:43:53,,,3.10.9

### 2.2 Negative

In [4]:
with open("../bow-data/negative.csv", newline="") as f:
    reader = csv.DictReader(f)
    data = list(reader)

negative_df = pd.DataFrame(data)

# convert dates to datetime
negative_df['at'] = pd.to_datetime(negative_df['at'])

negative_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,c2e5379e-089d-49a7-9b12-a2911d8177d9,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,absolutely useless steam pc problems able use ...,1,5,3.10.9,2026-03-10 12:03:24,,,3.10.9
1,008891c9-1f0f-43ec-a7b3-2e0c1816b93d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,try well hour log app change password account ...,1,220,3.10.6,2026-01-20 07:50:24,,,3.10.6
2,11a6bbe2-abad-48c2-a60a-eef4868fbdf0,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,download today login password way long even th...,1,22,,2026-01-21 07:39:28,,,
3,0283b618-aa4d-4b82-abb3-5c48c3084f8d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,work good steam browse shop however yesterday ...,1,626,3.6.5,2023-08-23 23:23:10,,,3.6.5
4,1b9897f8-c4f0-49e7-b624-a4639c6d78a9,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,never write review wow actually impress unusab...,1,581,3.7.2,2023-12-09 07:56:51,,,3.7.2

## 3. BoW Analysis

In [18]:

def generate_bow(contents):
    out = {}
    for text in contents:
        text_tokens = text.split(" ")

        for token in text_tokens:
            if token in out:
                out[token] += 1
            else:
                out[token] = 1
    
    return out

positive_bow = generate_bow(positive_df["content"])
print("Positive bag of words:")
print(positive_bow)

print("\n")

negative_bow = generate_bow(negative_df["content"])
print("Negative bag of words:")
print(negative_bow)

Positive bag of words:
{'steam': 46, 'app': 36, 'great': 10, 'way': 4, 'interact': 1, 'friends': 4, 'access': 8, 'account': 21, 'mobile': 2, 'instead': 1, 'use': 9, 'web': 1, 'browser': 2, 'desktop': 4, 'version': 5, 'little': 2, 'slower': 1, 'slightly': 1, 'clunky': 1, 'however': 2, 'update': 5, 'information': 2, 'chat': 2, 'two': 1, 'authentication': 2, 'enable': 2, 'might': 1, 'get': 20, 'loop': 1, 'disable': 1, 'delete': 1, 'reinstall': 1, 'work': 10, 'like': 6, 'interface': 1, 'lot': 4, 'think': 6, 'easy': 6, 'main': 1, 'reason': 2, 'give': 3, '5': 6, 'star': 5, 'support': 17, 'lose': 4, 'authenticator': 3, 'due': 2, 'years': 4, 'want': 4, 'back': 8, 'realize': 1, 'lock': 1, 'team': 5, 'hard': 2, 'help': 10, 'regain': 1, 'stupidity': 1, 'keep': 4, 'one': 7, 'game': 43, 'actually': 2, 'buy': 9, 'point': 2, 'username': 1, 'pretty': 2, 'attach': 1, 'say': 3, 'awesome': 1, 'best': 18, 'refund': 3, 'constant': 1, 'discount': 5, 'allow': 2, 'us': 3, 'even': 7, 'normally': 1, 'budget': 1, 'love': 8, 'company': 4, 'leave': 2, 'care': 1, 'customers': 1, 'see': 5, 'cash': 1, 'cow': 1, 'honestly': 4, 'greatest': 1, 'apps': 2, 'ever': 5, 'make': 8, 'countless': 1, 'endless': 1, 'opportunities': 1, 'customer': 7, 'service': 12, 'chart': 1, 'amaze': 2, 'experience': 10, 'life': 1, 'lightweight': 1, 'manage': 1, 'superior': 1, 'thank': 10, 'tf2': 6, 'wrong': 3, 'absolutely': 2, 'terrible': 2, 'laptop': 3, 'aim': 1, 'genuinely': 1, 'character': 1, 'lowky': 1, 'gooned': 1, 'twice': 1, 'really': 7, 'proud': 1, 'good': 13, 'describe': 1, 'without': 3, 'tell': 2, 'whole': 2, 'lore': 1, 'alongside': 1, 'weapon': 1, 'stats': 1, 'yeah': 2, 'ngl': 1, 'know': 1, 'pay': 3, 'play': 10, 'neccessarily': 1, 'take': 3, 'money': 5, 'sucker': 1, 'platformers': 1, 'toree': 1, '2': 1, 'free': 1, 'optimize': 1, 'actual': 1, 'console': 1, 'sure': 2, 'many': 1, 'people': 4, 'issue': 8, 'since': 3, '2017': 1, 'android': 6, 'devices': 1, 'ios': 1, 'ipados': 1, 'useful': 2, 'case': 2, 'catch': 1, 'deal': 4, 'start': 2, 'remote': 1, 'download': 4, 'new': 5, 'patch': 1, 'computer': 1, 'story': 1, 'better': 5, 'movie': 1, 'although': 1, 'require': 1, 'action': 2, 'time': 5, 'sip': 1, 'beer': 1, 'multi': 1, 'task': 1, 'something': 4, 'need': 5, 'aware': 1, 'utilize': 1, 'feature': 3, 'log': 4, 'phone': 6, 'number': 3, 'also': 3, 'recovery': 1, 'cod': 1, 'quick': 1, 'respond': 2, 'super': 1, 'helpful': 2, 'remove': 2, 'old': 1, 'w': 2, 'happy': 2, 'relieve': 1, 'purchase': 3, '3': 3, 'improve': 3, 'quite': 1, 'important': 1, 'part': 1, 'wallet': 2, 'miss': 2, 'almost': 1, 'go': 3, 'less': 2, 'minute': 1, 'top': 1, 'local': 1, 'e': 1, 'overall': 2, 'rat': 4, 'low': 2, 'usually': 1, 'bother': 1, 'happen': 3, 'run': 2, 'perfectly': 1, 'though': 1, 'everything': 2, 'appreciation': 1, 'review': 2, 'much': 4, 'every': 1, 'online': 1, 'store': 5, 'name': 1, 'limit': 1, 'payment': 1, 'options': 1, 'compatible': 1, 'literally': 2, 'anything': 3, 'always': 3, 'solve': 1, 'problems': 1, 'within': 3, 'day': 1, 'thing': 1, 'sell': 1, 'inventory': 1, 'item': 1, 'wait': 1, 'long': 3, 'absolute': 3, 'world': 2, 'glitching': 2, 'try': 3, '30': 1, 'minutes': 2, 'resolve': 2, '1': 2, 'hours': 3, 'put': 1, 'address': 1, 'decline': 1, 'bank': 1, 'later': 2, 'automatically': 1, 'basically': 1, 'safety': 1, 'net': 1, 'servic': 1, 'squad': 1, 'provide': 1, 'course': 2, 'lost': 1, 'discord': 1, 'login': 3, 'yesterday': 1, 'let': 3, 'in': 1, 'least': 1, 'pc': 4, 'nice': 2, 'recover': 1, 'program': 1, 'available': 1, 'smartphones': 1, 'still': 3, 'perspective': 1, 'explain': 1, 'accaunt': 1, 'hessitate': 1, 'expect': 1, 'fast': 1, 'tick': 1, 'platform': 2, 'word': 1, 'thenk': 1, 'enaugh': 1, 'fist': 1, 'corrupt': 1, '£150': 1, 'others': 1, '£17': 1, 'save': 2, '10': 4, 'mods': 1, 'turn': 2, 'plus': 1, 'simple': 1, 'cheap': 1, 'gabe': 1, 'find': 1, 'problem': 4, 'far': 2, 'guy': 1, 'ui': 3, 'user': 1, 'feel': 1, 'outdated': 1, 'yes': 1, 'add': 2, 'wishlist': 3, 'counter': 1, 'page': 2, 'scroller': 1, 'stay': 1, 'exact': 1, 'position': 1, 's': 1, 'please': 1, 'consider': 1, 'suggestion': 1, 'around': 1, 'trouble': 1, 'bundle': 1, 'able': 2, 'notice': 2, 'plight': 1, 'valve': 2, 'gamenative': 1, 'gamehub': 1, 'already': 2, 'enough': 1, 'compact': 1, 'view': 1, 'marketplace': 1, 'open': 1, 'smoother': 1, 'fine': 2, 'check': 3, 'shop': 1, 'importantly': 1, 'key': 1, 'anywhere': 1, 'perfect': 2, 'arm': 1, 'base': 1, 'project': 1, 'succeed': 1, 'shift': 1, 'focus': 1, 'encounter': 1, 'sosme': 1, 'system': 1, 'requierments': 1, 'software': 1, 'suggest': 1, 'witch': 1, 'sign': 4, '40': 1, 'error': 1, 'first': 1, 'internet': 1, 'roblox': 1, 'smoothly': 1, 'frickin': 1, 'acc': 1, 'anyways': 1, 'fix': 3, 'ok': 2, 'stuff': 1, 'finally': 2, 'change': 2, 'yey': 1, 'boyfriend': 1, 'hack': 2, 'solution': 1, 'report': 1, 'ban': 1, 'hacker': 1, 'instantly': 2, 'forget': 1, 'password': 3, 'verification': 1, 'r': 1, 'write': 1, 'fantastic': 1, 'receive': 1, 'request': 1, 'necessarily': 1, 'monitor': 1, 'look': 1, 'answer': 1, 'question': 1, 'companion': 1, 'browse': 1, 'remotely': 1, 'majority': 1, 'honest': 2, 'design': 1, 'os': 1, 'deck': 1, 'delivery': 1, 'promptly': 1, 'gamer': 1, 'continue': 2, 'stellar': 1, 'products': 1, 'tag': 3, 'section': 1, 'break': 1, 'visually': 1, 'click': 2, 'tabs': 1, 'global': 1, 'recommend': 1, 'list': 1, 'well': 2, 'overlay': 1, 'either': 1, 'idea': 1, 'complaints': 1, 'yap': 1, 'personally': 1, 'high': 2, 'quality': 1, 'consistently': 1, 'qr': 1, 'code': 1, 'must': 2, 'users': 1, 'frequently': 1, 'never': 1, 'transfer': 1, 'cinema': 1, 'accout': 1, 'steal': 1, 'email': 1, 'reach': 1, 'matter': 1, 'kelly': 1, 'wat': 1, 'till': 1, 'fex': 1, 'proton': 1, 'windows': 1, 'powerful': 1, 'hope': 1, 'come': 1, 'year': 1, 'sales': 1, 'insane': 1, 'general': 1, 'pro': 1, 'consumer': 1, 'entities': 1, 'guard': 1, 'impersonate': 1, 'moderators': 1, 'whatnots': 1, 'security': 1, 'five': 1, 'currently': 1, 'goated': 1, 'unacceptable': 1, 'reset': 1, 'face': 1, 'hour': 1, 'progress': 1, 'heart': 1, 'among': 1, 'applications': 1, 'screen': 1, 'customisable': 1, 'rust': 3, 'playtime': 1, 'exception': 1, 'cost': 1}


Negative bag of words:
{'absolutely': 3, 'useless': 2, 'steam': 61, 'pc': 12, 'problems': 1, 'able': 8, 'use': 28, 'app': 79, 'longtime': 1, 'afraid': 1, 'uninstall': 1, 'phone': 10, 'might': 3, 'effectively': 1, 'keep': 8, 'log': 19, 'desktop': 4, 'guard': 7, 'much': 8, 'money': 3, 'tie': 1, 'game': 30, 'library': 3, 'get': 34, 'screw': 1, 'absolute': 1, 'pain': 1, 'try': 26, 'well': 7, 'hour': 2, 'change': 6, 'password': 10, 'account': 29, 'continuously': 1, 'error': 4, 'server': 2, 'issue': 11, 'thus': 1, 'frustrate': 3, 'confuse': 1, 'love': 3, 'share': 1, 'play': 6, 'friends': 10, 'go': 11, 'unable': 2, 'feel': 1, 'bug': 3, 'rather': 1, 'end': 3, 'hope': 3, 'fix': 7, 'download': 10, 'today': 2, 'login': 7, 'way': 9, 'long': 3, 'even': 18, 'though': 3, 'know': 3, 'correct': 2, 'update': 11, 'still': 6, 'work': 24, 'double': 1, 'check': 1, 'username': 2, 'yep': 1, 'right': 5, 'whole': 4, 'process': 5, 'third': 2, 'time': 20, 'copy': 1, 'paste': 1, 'note': 1, 'make': 12, 'sure': 2, 'input': 4, 'correctly': 2, 'nada': 1, 'infuriate': 1, 'couple': 1, 'years': 9, 'never': 9, 'good': 3, 'browse': 4, 'shop': 1, 'however': 3, 'yesterday': 1, 'stop': 2, 'entirely': 1, 'first': 1, 'in': 5, 'reopen': 1, 'blank': 1, 'screen': 5, 'see': 11, 'others': 2, 'report': 1, 'result': 2, 'lose': 4, 'access': 7, 'confirm': 3, 'trade': 2, 'offer': 1, 'etc': 3, 'unless': 1, 'reinstall': 2, 'move': 1, 'authenticator': 4, 'write': 1, 'review': 3, 'wow': 1, 'actually': 8, 'impress': 1, 'unusable': 5, 'stick': 7, 'inputting': 1, 'code': 13, 'send': 4, 'email': 14, 'randomly': 1, 'put': 1, 'box': 1, 'delete': 3, 'helplessly': 1, 'order': 2, 'finally': 2, 'happen': 4, 'errors': 1, 'start': 1, 'previous': 3, 'anyways': 1, 'believe': 1, 'possible': 2, 'worse': 4, 'latest': 1, 'store': 10, 'slower': 1, 'laggy': 2, 'compare': 1, 'version': 6, 'suddenly': 1, 'bunch': 1, 'notifications': 1, 'bombard': 1, 'sales': 1, 'wishlist': 3, 'need': 9, 'notification': 2, 'every': 5, 'sale': 3, 'worst': 4, 'removable': 1, 'list': 5, 'care': 2, 'chat': 8, 'anymore': 3, 'online': 3, 'awful': 3, 'gutted': 1, 'ruin': 2, '2': 7, 'separate': 3, 'apps': 3, 'functionality': 5, 'one': 13, 'fine': 7, 'except': 1, 'neither': 1, 'things': 5, 'old': 8, 'edit': 4, 'additionally': 1, 'purchase': 3, 'already': 3, 'ask': 5, 'jump': 2, '2fa': 4, 'hoop': 1, 'endless': 1, 'loop': 3, 'also': 4, 'let': 8, 'contact': 4, 'support': 11, 'exactly': 1, 'like': 5, 'slow': 5, 'asf': 1, 'full': 1, 'webpages': 1, 'display': 1, 'example': 2, 'ill': 1, 'workshop': 1, 'page': 12, 'mod': 1, 'text': 3, 'perfectly': 1, 'image': 1, 'half': 2, 'unseeable': 1, 'scroll': 2, 'leave': 4, 'whenever': 1, 'website': 5, 'instead': 3, 'autodirects': 1, 'back': 14, 'want': 9, 'great': 1, 'buggier': 1, 'nearly': 1, 'open': 11, 'manually': 2, 'kill': 2, 'restart': 1, 'bad': 5, 'state': 1, 'spend': 4, 'effort': 1, 'style': 1, 'cut': 1, 'qa': 1, 'corner': 1, 'possibly': 1, 'tasker': 1, 'create': 10, 'shortcut': 1, 'relaunch': 1, 'press': 3, 'later': 1, 'true': 2, 'joke': 2, 'everything': 4, 'give': 4, 'chance': 1, 'maneuver': 1, 'interface': 1, 'without': 5, 'immense': 1, 'amount': 2, 'redundancy': 1, 'take': 9, '4': 2, '6': 1, 'homepage': 1, 'several': 2, 'horrible': 3, 'experience': 5, 'constantly': 2, 'redirect': 1, 'discussion': 1, 'cart': 2, 'sync': 1, 'reason': 4, 'community': 1, 'market': 2, 'complete': 1, 'waste': 2, 'mandatory': 1, 'sell': 4, 'inventory': 1, 'items': 6, 'marketplace': 2, 'set': 4, 'three': 2, 'days': 2, 'do': 2, 'sms': 1, 'cod': 2, 'verification': 4, 'everytime': 1, 'enter': 3, 'lock': 1, 'two': 4, 'weeks': 2, 'garbage': 3, 'bricked': 1, '1000s': 1, 'dollars': 1, 'prove': 1, 'policy': 1, 'force': 3, 'throats': 1, 'refuse': 4, 'shin': 1, 'buy': 11, 'anything': 8, 'bring': 1, 'physical': 1, 'else': 4, 'matter': 3, 'hold': 3, 'hey': 1, 'run': 3, 'despite': 2, 'verify': 7, 'recognize': 1, 'twice': 2, 'prevent': 1, 'maybe': 1, 'something': 4, 'wrong': 2, 'whatever': 2, 'terrible': 4, 'platform': 1, 'search': 1, 'either': 3, 'properly': 1, 'really': 3, 'disappoint': 1, 'remove': 2, 'mobile': 10, 'altogether': 1, 'wait': 5, 'home': 2, 'familiar': 1, 'easy': 1, 'fully': 1, 'functional': 1, 'all': 1, 'say': 11, 'claim': 1, 'lie': 1, 'infinite': 2, 'repeat': 2, 'yet': 1, 'creation': 3, 'reset': 2, 'captcha': 4, 'glitches': 1, 'hate': 1, 'seem': 3, 'pile': 1, 'ontop': 1, 'please': 1, 'star': 2, '1': 2, 'truly': 1, 'general': 1, 'buggy': 1, 'mess': 1, 'fail': 7, 'deck': 4, 'cause': 1, 'pending': 1, 'transaction': 2, '£349': 1, 'call': 1, 'bank': 1, 'clear': 2, 'forget': 1, 'ordeal': 1, 'thing': 3, 'tell': 3, '3d': 1, 'authentication': 4, 'pocket': 1, 'options': 2, 'paypal': 3, 'external': 2, 'browser': 6, 'window': 1, 'attempt': 2, 'intercept': 1, 'link': 4, 'often': 3, 'completely': 4, 'close': 1, 'thank': 2, 'moment': 1, 'click': 7, 'icon': 1, 'grey': 1, 'load': 9, 'parental': 2, 'settings': 3, 'tiny': 1, 'black': 2, 'letter': 2, 'enable': 1, 'small': 1, 'handful': 1, 'begin': 1, 'remember': 6, 'cumbersome': 1, 'expierence': 1, 'delay': 1, 'acessed': 1, 'week': 1, 'fact': 1, 'break': 4, 'abandon': 1, 'chore': 1, 'find': 4, 'previously': 2, 'view': 2, 'longer': 2, 'valid': 1, 'problem': 2, 'widget': 2, 'qr': 5, 'select': 2, 'option': 2, 'system': 2, 'approve': 1, 'deny': 1, 'request': 2, 'base': 1, 'upon': 1, 'ip': 2, 'location': 1, 'tldr': 1, 'nightmare': 1, '20': 1, 'mins': 1, 'simple': 3, 'message': 4, 'friend': 1, 'new': 4, 'lay': 1, 'bury': 1, 'different': 1, 'tab': 1, 'squish': 1, 'type': 2, 'excite': 1, 'switch': 1, 'xbox': 1, 'hassle': 2, 'slowest': 1, 'google': 1, 'minor': 1, 'interruption': 1, 'connection': 2, 'become': 3, 'regular': 1, 'easier': 1, 'faster': 1, 'convenient': 1, 'require': 2, 'install': 1, 'stuff': 2, 'part': 1, 'hand': 1, 'miserable': 1, 'menu': 3, 'test': 1, 'beyond': 1, 'critical': 1, 'literally': 5, 'currently': 5, 'last': 1, 'nothing': 1, 'responses': 1, 'invalid': 1, 'ridiculous': 1, 'someone': 4, 'pay': 1, 'site': 3, 'servers': 1, 'software': 1, 'allow': 3, 'add': 1, 'sign': 13, 'uninstalled': 2, 'profile': 1, 'reload': 1, 'sudden': 3, 'enjoy': 1, 'roll': 1, 'communicate': 2, 'anyone': 4, 'byzantine': 1, 'migraine': 1, 'dive': 1, 'gain': 1, 'ton': 1, 'honestly': 2, 'think': 2, 'rely': 2, 'manage': 1, 'kind': 1, 'impossible': 5, 'feedback': 1, 'talk': 3, 'accomplish': 1, 'bluetooth': 1, 'keyboard': 2, 'mouse': 1, 'instal': 2, 'instantly': 1, 'regret': 1, 'bend': 1, 'spar': 1, 'seemingly': 2, 'daily': 1, 'dance': 1, 'chrome': 1, 'e': 1, 'g': 1, 's': 7, 'resolve': 2, 'default': 1, 'main': 2, 'usually': 1, 'recent': 1, 'activity': 1, 'overview': 1, 'strip': 1, 'pretty': 3, 'rid': 3, 'ability': 1, 'nice': 3, 'dirty': 1, 'heathens': 1, 'poorly': 1, 'design': 1, 'ui': 3, 'extremely': 2, 'expect': 1, 'us': 1, 'friday': 1, 'autumn': 1, 'web': 2, 'content': 3, 'solution': 1, 'less': 2, 'likely': 1, 'simply': 1, 'boot': 1, 'user': 2, 'id': 2, 'obviously': 1, 'help': 4, 'scan': 1, 'around': 3, 'authenticate': 2, 'steamguard': 2, 'jumble': 1, 'dissapearing': 1, 'anywhere': 1, 'response': 2, 'monitor': 1, 'none': 2, 'self': 1, 'question': 1, 'fit': 1, 'situation': 2, 'ticket': 1, 'past': 1, 'point': 1, 'continue': 1, 'automatic': 1, 'prompt': 2, 'place': 2, 'ago': 2, 'people': 1, 'recently': 2, 'customer': 1, 'return': 1, 'operations': 1, 'ever': 3, 'video': 1, 'happy': 1, 'laptop': 1, 'anti': 1, 'robot': 1, 'pics': 1, 'bicycle': 1, 'buss': 1, 'improve': 1, 'optimize': 1, 'stutter': 1, 'overall': 1, 'always': 2, 'room': 1, 'improvement': 1, '5': 2, '10': 2, '13': 1, '22': 1, 'focus': 1, 'least': 1, 'icons': 1, 'top': 1, 'plain': 1, 'annoy': 3, 'breath': 1, 'nobody': 1, 'valve': 1, 'read': 1, 'lightweight': 1, 'useful': 1, 'bite': 1, 'lead': 1, 'limit': 1, 'schedule': 1, 'probably': 2, 'raise': 1, 'suggest': 1, 'match': 1, 'client': 2, 'romance': 1, 'kingdoms': 1, 'gameplay': 1, 'technical': 1, 'refund': 1, 'provide': 1, 'since': 1, 'initially': 1, 'direct': 2, 'publisher': 1, 'hear': 2, 'number': 1, 'trust': 1, 'genuinely': 1, 'sometimes': 2, 'reverify': 1, 'complicate': 1, 'quite': 1, 'captha': 1, 'incredible': 1, 'overly': 1, 'sensitive': 1, 'spot': 1, 'front': 1, 'interest': 1, 'explore': 1, 'enough': 1, 'hunt': 1, 'hide': 1, 'gems': 1, 'wall': 1, 'garden': 1, '15': 1, 'listings': 1, 'repeatedly': 1, 'easily': 1, 'hack': 1, 'block': 1, 'steal': 1, 'personal': 1, 'information': 1, 'credit': 1, 'card': 1, 'thousands': 1, 'dallors': 1, 'worth': 1, 'step': 1, 'varification': 1, 'alert': 1, 'w': 1, 'almost': 1, 'existent': 1, 'non': 1, 'remorseful': 1, 'unreliable': 1, 'untrustworthy': 1, 'uninstalling': 1, 'across': 1, 'devices': 1, 'desire': 1, 'pete': 1, 'sake': 1, 'loosen': 1, 'recaptcha': 1, 'reach': 1, 'multiple': 1, 'automate': 1, 'suck': 1, 'lot': 1, 'company': 1, 'word': 1, 'better': 2, 'second': 2, 'away': 1, 'revert': 1, 'discord': 1, 'stay': 1, '75': 1, '1gb': 1, 'fiber': 1, 'internet': 1, 'speed': 1, 'amaze': 1, '25': 1, 'year': 1, 'plan': 1, 'another': 1, 'bother': 1, 'older': 1, 'discussions': 1, 'button': 1, 'frequent': 1, 'forums': 1, 'huge': 1, 'next': 1, 'warn': 1, 'choice': 1, 'warnings': 1, 'difficult': 1, 'frequently': 1, 'within': 1, 'news': 1, 'bulletin': 1, 'device': 1, 'plug': 1, 'computer': 2, 'address': 1, 'charge': 1, 'via': 1, 'turn': 2, 'empty': 1, 'wallet': 1, 'et': 1, 'cetera': 1, 'little': 1, 'person': 1, 'china': 1, 'basically': 1, 'mycash': 1, 'constant': 1, 'stupid': 1, 'crash': 1, 'swear': 1, 'info': 2, 'lengthy': 1, 'laaggy': 1, 'unlock': 1, 'idiot': 1, 'side': 1, 'world': 1, 'save': 1, 'night': 1, 'auto': 1, 'filled': 1, 'somebody': 1, 'confirmation': 1, 'discuss': 1, 'many': 1, 'name': 1}